# Step 1: build
FROM node:16.13.1 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-optional
COPY . .
RUN npm run build

# Step 2: run
FROM node:16.13.1-alpine
WORKDIR /app
COPY --from=builder /app ./
CMD ["npm", "run", "start:stg"]
